from __future__ import annotations
from egglog import *
from enum import Enum

from .VectorSort import Vector

SPARSITY_THRESHOLD = 0.6

class StorageFormat(Enum):
    NATIVE = i64(1)
    CSC = i64(2)
    CSR = i64(3)


class Matrix(Expr):
    def __init__(self, rows: i64Like, cols: i64Like, sparsity: f64Like) -> None: ...
    def __matmul__(self, other: Matrix) -> Matrix: ...
    def __add__(self, other: Matrix) -> Matrix: ...
    def mat_inv(self) -> Matrix: ...
    def mat_mpinv(self) -> Matrix: ...
    def mat_trans(self) -> Matrix: ...
    def kron(self, other: Matrix) -> Matrix: ...
    def krao(self, other: Matrix) -> Matrix: ...
    def hdmr(self, other: Matrix) -> Matrix: ...
    def mat_concat(self, other: Matrix) -> Matrix: ...
    def mat_vec_mul(self, other: Vector) -> Vector: ...
    def spmv(self, other: Vector) -> Vector: ...

    @property
    def row(self) -> i64: ...
    @property
    def col(self) -> i64: ...
    @property
    def sparsity(self) -> f64: ...